//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public long SessionLogID { get; set; }
        public int AccountingTypeID { get; set; }
        public int Amount { get; set; }
        public System.DateTime AccountingTimeStamp { get; set; }
        public int CurrencyID { get; set; }
        public int ForCardBalance { get; set; }
        public Nullable<System.Guid> Trid { get; set; }
    
        public virtual AccountingType AccountingType { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual SessionLog SessionLog { get; set; }
    }
}
