//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingType
    {
        public AccountingType()
        {
            this.Accountings = new HashSet<Accounting>();
        }
    
        public int AccountingTypeID { get; set; }
        public string AccountingTypeName { get; set; }
        public string AccountingTypeDescription { get; set; }
    
        public virtual ICollection<Accounting> Accountings { get; set; }
    }
}
