//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseCardType
    {
        public BaseCardType()
        {
            this.BaseCards = new HashSet<BaseCard>();
        }
    
        public int CardTypeID { get; set; }
        public string CardTypeName { get; set; }
    
        public virtual ICollection<BaseCard> BaseCards { get; set; }
    }
}
