//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Organizations = new HashSet<Organization>();
            this.Players = new HashSet<Player>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string CountryShortName { get; set; }
        public int CurrencyID { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
