//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Accountings = new HashSet<Accounting>();
            this.Countries = new HashSet<Country>();
            this.Machines = new HashSet<Machine>();
            this.Organizations = new HashSet<Organization>();
            this.Players = new HashSet<Player>();
        }
    
        public int CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyShortName { get; set; }
    
        public virtual ICollection<Accounting> Accountings { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<Player> Players { get; set; }
    }
}
