//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Machines = new HashSet<Machine>();
            this.SessionLogs = new HashSet<SessionLog>();
        }
    
        public int GameID { get; set; }
        public int PartnerID { get; set; }
        public string GameName { get; set; }
        public string GameDescription { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual ICollection<SessionLog> SessionLogs { get; set; }
    }
}
