//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IGameUserMachineSiteAssignment
    {
        public int BaseCardID { get; set; }
        public int MachineID { get; set; }
        public int SiteId { get; set; }
    
        public virtual BaseCard BaseCard { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
