//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineSession
    {
        public MachineSession()
        {
            this.MachineSessionLogs = new HashSet<MachineSessionLog>();
            this.Sessions = new HashSet<Session>();
        }
    
        public long MachineSessionID { get; set; }
        public int MachineID { get; set; }
        public System.DateTime SessionStart { get; set; }
        public Nullable<System.DateTime> SessionEnd { get; set; }
        public Nullable<int> SessionEndTypeID { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual MachineSessionEndType MachineSessionEndType { get; set; }
        public virtual ICollection<MachineSessionLog> MachineSessionLogs { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
