//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineSessionEndType
    {
        public MachineSessionEndType()
        {
            this.MachineSessions = new HashSet<MachineSession>();
        }
    
        public int SessionEndTypeID { get; set; }
        public string SessionEndName { get; set; }
    
        public virtual ICollection<MachineSession> MachineSessions { get; set; }
    }
}
