//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineSessionLog
    {
        public long MachineSessionLogID { get; set; }
        public long MachineSessionID { get; set; }
        public int MachineSessionLogActionID { get; set; }
        public System.DateTime LogTimeStamp { get; set; }
    
        public virtual MachineSession MachineSession { get; set; }
        public virtual MachineSessionLogAction MachineSessionLogAction { get; set; }
    }
}
