//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineSessionLogAction
    {
        public MachineSessionLogAction()
        {
            this.MachineSessionLogs = new HashSet<MachineSessionLog>();
        }
    
        public int MachineSessionLogActionID { get; set; }
        public string MachineSessionLogName { get; set; }
    
        public virtual ICollection<MachineSessionLog> MachineSessionLogs { get; set; }
    }
}
