//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Machines = new HashSet<Machine>();
            this.Players = new HashSet<Player>();
            this.SessionLogs = new HashSet<SessionLog>();
            this.WebSessions = new HashSet<WebSession>();
        }
    
        public int OrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public int OrganizationTypeID { get; set; }
        public int ParentId { get; set; }
        public int CountryID { get; set; }
        public string Phone { get; set; }
        public string Street { get; set; }
        public string ZIP { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> LockedTimeStamp { get; set; }
        public bool Deleted { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> B2DWebShopId { get; set; }
        public int OrganizationStateID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual OrganizationState OrganizationState { get; set; }
        public virtual OrganizationType OrganizationType { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual ICollection<SessionLog> SessionLogs { get; set; }
        public virtual ICollection<WebSession> WebSessions { get; set; }
    }
}
