//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationState
    {
        public OrganizationState()
        {
            this.Organizations = new HashSet<Organization>();
        }
    
        public int OrganizationStateID { get; set; }
        public string OrganizationStateName { get; set; }
    
        public virtual ICollection<Organization> Organizations { get; set; }
    }
}
