//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.Games = new HashSet<Game>();
            this.Machines = new HashSet<Machine>();
        }
    
        public int PartnerID { get; set; }
        public string PartnerName { get; set; }
        public string PartnerDescription { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
    }
}
