//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerRole
    {
        public PlayerRole()
        {
            this.Players = new HashSet<Player>();
        }
    
        public int PlayerRoleID { get; set; }
        public string PlayerRoleName { get; set; }
    
        public virtual ICollection<Player> Players { get; set; }
    }
}
