//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int BaseCardID { get; set; }
        public int OrganizationID { get; set; }
        public int PlayerRoleID { get; set; }
        public int CurrencyID { get; set; }
        public int LanguageID { get; set; }
        public int CountryID { get; set; }
        public int Balance { get; set; }
        public int FailedPinLogins { get; set; }
        public string Alias { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Street { get; set; }
        public string ZIP { get; set; }
        public string City { get; set; }
        public bool IsMale { get; set; }
        public Nullable<long> IGameAccountingReservationSessionLogNR { get; set; }
        public Nullable<long> SessionNR { get; set; }
        public Nullable<int> FailedLogoutAttempts { get; set; }
    
        public virtual BaseCard BaseCard { get; set; }
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Language Language { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual SessionLog SessionLog { get; set; }
        public virtual PlayerRole PlayerRole { get; set; }
        public virtual Session Session { get; set; }
    }
}
