//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Players = new HashSet<Player>();
            this.SessionLogs = new HashSet<SessionLog>();
        }
    
        public long SessionID { get; set; }
        public System.DateTime SessionStart { get; set; }
        public Nullable<System.DateTime> SessionEnd { get; set; }
        public int BaseCardID { get; set; }
        public Nullable<long> MachineSessionID { get; set; }
        public int SessionTypeID { get; set; }
    
        public virtual BaseCard BaseCard { get; set; }
        public virtual MachineSession MachineSession { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual SessionType SessionType { get; set; }
        public virtual ICollection<SessionLog> SessionLogs { get; set; }
        public virtual WebSession WebSession { get; set; }
    }
}
