//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionLog
    {
        public SessionLog()
        {
            this.Players = new HashSet<Player>();
        }
    
        public long SessionLogID { get; set; }
        public long SessionID { get; set; }
        public int ActionID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> GameID { get; set; }
        public System.DateTime LogTimeStamp { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> ForBaseCardID { get; set; }
    
        public virtual Accounting Accounting { get; set; }
        public virtual Action Action { get; set; }
        public virtual BaseCard BaseCard { get; set; }
        public virtual Game Game { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual Session Session { get; set; }
    }
}
