//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingID { get; set; }
        public int RegionID { get; set; }
        public Nullable<System.DateTime> LastTimeOutCheck { get; set; }
        public Nullable<int> OtcExpirationLimit { get; set; }
        public Nullable<decimal> OtcExpirationThreshold { get; set; }
        public Nullable<int> PayOutLimit { get; set; }
        public Nullable<int> PayInLimit { get; set; }
        public Nullable<int> LossLimit { get; set; }
        public int DesiredHold { get; set; }
        public string DisplayedCoinSymbol { get; set; }
        public Nullable<int> MaxOrganizationLoss { get; set; }
        public bool AllowActionGames { get; set; }
        public int MaxGamble { get; set; }
        public bool AllowTurbo { get; set; }
        public Nullable<int> McmPayInLimit { get; set; }
    }
}
