//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int BaseCardID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> LastPoll { get; set; }
        public string Street { get; set; }
        public string ZIP { get; set; }
        public string City { get; set; }
        public int LanguageID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int CountryID { get; set; }
        public string Gender { get; set; }
        public string Fullname { get; set; }
    
        public virtual BaseCard BaseCard { get; set; }
        public virtual Country Country { get; set; }
        public virtual Language Language { get; set; }
    }
}
