//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSession
    {
        public long SessionID { get; set; }
        public System.Guid WebToken { get; set; }
        public int OrganizationID { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Session Session { get; set; }
    }
}
